server:
  port: 8080
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates: [ Path=/api/auth/** ]
        - id: menu-service
          uri: lb://menu-service
          predicates: [ Path=/api/menu/** ]
        - id: order-service
          uri: lb://order-service
          predicates: [ Path=/api/orders/** ]
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka