server:
  port: 9001
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 9603633400
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret: change-this-super-secret-at-least-32-chars-1234567890
  expirationMs: 86400000